version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_lost_ark
      MYSQL_USER: jokuur
      MYSQL_PASSWORD: test
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
